### ISSUE TITLE
old launcher question

### ISSUE THREAD

**Issue by Fcases** [azhurb/stalker_portal#181]
how can we change the accountinfo payments signup/ terms etc ?

**Comment by azhurb** [comment]
https://groups.google.com/d/topic/stalker-middleware/YZmxa_ck7gU/discussion

**Comment by Fcases** [comment]
this just about the button names, not the page content

**Comment by azhurb** [comment]
You have to change translation for
account_payment_info / account_agreement_info / account_terms_info
