### ISSUE TITLE
Не работает фильтр в списку IPTV каналов

### ISSUE THREAD

**Issue by mallna** [azhurb/stalker_portal#234]
Когда выбирать  Статус или Статус мониторинга номера страниц не отображаются тогда... и не отображается какой статус выбран

**Comment by azhurb** [comment]
Номера страниц не отображаются потому что результат поместился на одну страницу, а отображение фильтров исправим в ближайшей версии.

**Comment by mallna** [comment]
результат не помістився на одну сторінку, тому що після задання цих фільтрів в мене відображається тільки два канали, а коли я починаю сортувати ці канали наприклад по ІД (з меншого до більшого) тоді появляються більше каналів. А якщо наприклад зняти всі фільтра і просто в ручну порахувати кількість каналів в яких є помилки то їх получається набагато більше чим відображається
