### ISSUE TITLE
Stalker 5.0.3 use_embedded_settings

### ISSUE THREAD

**Issue by barhom** [azhurb/stalker_portal#260]
Hello,

When use_embedded_settings is set to "false" mag250 boxes does not open the "Settings" page.
Please verify.

When use_embedded_settings is set to "true" then we can access the settings page.

**Comment by azhurb** [comment]
Hello.
use_embedded_settings setting is deprecated and in future it will always be "false".
Please contact support support@infomir.eu and send debug log from the stb.
