### ISSUE TITLE
How to enable youtube?

### ISSUE THREAD

**Issue by manvir-singh** [azhurb/stalker_portal#268]
Where is the YouTube module? I can't find it anywhere to enable.

**Comment by FLIKI** [comment]
Hi,
I am not sure if it will help, but at leas you can try ;)

If you are with version > 5

- In custom.ini check for the line:
 all_modules[] = youtube

- Go to the admin panel (the new one):
http:// --your portal URL-- /stalker_portal/server/adm/application-catalog/smart-application-list
(Applications / Smart Launcher apps)
Update all apps!

- Go to the admin panel (the new one again):
( Applications   Stalker Classic apps)
http:// --your portal URL-- /stalker_portal/server/adm/application-catalog/application-list
Install and activate the youtube app from this URL:
https://github.com/GeraldBrooks/youtube

-Go to the admin panel. In The Tariff section go to Service Packages and make sure you have a service package that contain the SERVICE : module and that the YOUTUBE module is selected. 

-Check if the box on witch you are testing has the Service Package with the youtube module enabled.

**Comment by morfair** [comment]
Does is https://github.com/GeraldBrooks/youtube work with Stalker Launcher (not Classic)?

**Comment by Delitants** [comment]
It's not working

**Comment by manvir-singh** [comment]
Project seems dead :(
