### ISSUE TITLE
Stalker redirecting from port 80 (nginx reverse proxy) to port 88 (apache2)

### ISSUE THREAD

**Issue by javiermatos** [azhurb/stalker_portal#270]
I have installed stalker v5.1.0 and I have it working. I use nginx as a reverse proxy on port 80 and apache2 listening on port 88 to process the requests.

When I access the url http://stalker-portal.lxd/stalker_portal/ then requests are the following:

1. http://stalker-portal.lxd/stalker_portal/ (status 200)
2. http://stalker-portal.lxd/stalker_portal/server/adm -> Response Location http://stalker-portal.lxd:88/stalker_portal/server/adm/ (status 301)
3. http://stalker-portal.lxd:88/stalker_portal/server/adm/ -> Response Location http://stalker-portal.lxd:88/stalker_portal/server/adm/login (status 302)
4. http://stalker-portal.lxd:88/stalker_portal/server/adm/login (status 200)

So the question is, why is it redirecting to port 88? If I remove the port 88 from the url on login page it will work the same. Is it really needed to show the port apache2 is listening behind nginx? How can be that removed so all the requests are always done to nginx port 80?

**Comment by azhurb** [comment]
Try to change in nginx config line 
`proxy_set_header Host $host;`
to
`proxy_set_header Host $host:$server_port;`

**Comment by javiermatos** [comment]
Thank you so much, that solved the issue :)
