### ISSUE TITLE
Видеоклуб

### ISSUE THREAD

**Issue by stigmato135** [azhurb/stalker_portal#271]
Здравствуйте. Не очень понятно как работает "недосмотренное видео".
При воспроизведении, в таблицу vclub_not_ended записывается id медиа-файла из video_series_files, что вроде бы логично. Но при попытке просмотреть недосмотренный
 контент, id берется уже из таблицы video, а не video_series_files.

**Comment by azhurb** [comment]
Здравствуйте. Исправили.
https://github.com/azhurb/stalker_portal/commit/d25b727d5e09a072a8d9e26beece9b0f1b47fad2
