### ISSUE TITLE
VLC 3.0.0 fails with connection error on stalker portal

### ISSUE THREAD

**Issue by fiery-** [azhurb/stalker_portal#276]
With the latest VLC versions using the 3.0.0 core ([nightly builds](https://nightlies.videolan.org/) for Mac, PC and Android) some Stalker servers fail with error 404. It turns out that the new VLC strictly searches for CRLF endings of server response and fails when server uses only LF (0x0A) endings. See [vlc_http_can_read](https://github.com/videolan/vlc/blob/master/modules/access/http/h1conn.c#L39) function which causes connection failure while reading the response.

I'm posting this issue here, since I'm testing an IPTV provider that uses Stalker portal (m3u links are locked by MAC address). Can someone confirm if the following problem exists in Stalker or it's a problem of the underlining web server that serves the video streams. Problem appears only with unique URLs on port 88 which look like http://11.11.11.11:88/abcdef. URLs that look like http://11.11.11.11:88/udp/abcdef work fine (see bellow).

If the problem is in Stalker portal, I would like to ask you to provide a sample URL with a very short ts file (1 min.), so I can file a bug report to VLC (they require a public URL to reproduce the problem). Of course, fixing this in Stalker would be great.

Here is an example response of http://11.11.11.11:88/abcdef URL that causes problem in latest VLC and may be other video players:
```
HTTP/1.0 200 OK
Content-type: application/octet-stream
Connection: close
Cache-Control: no-cache
```
The above response in hex format with separated by me 0x0A endings:
```
485454502F312E3020323030204F4B 0A
436F6E74656E742D747970653A206170706C69636174696F6E2F6F637465742D73747265616D 0A
436F6E6E656374696F6E3A20636C6F7365 0A
43616368652D436F6E74726F6C3A206E6F2D6361636865 0A
0A
```
The correct endings should be CRLF (0D 0A) especially the last two.

Some streams that look like http://11.11.11.11:88/udp/abcdef return similar response, but since the last two endings are CRLF CRLF they work fine in VLC:
```
HTTP/1.1 200 OK
Server: mcrstrm 1.0-23.9 (prod) standard [Linux 3.16.0-30-lowlatency x86_64]
Content-Type:application/octet-stream
Cache-Control: no-cache
Connection: close
```
The same response in hex format (notice the mixed endings):
```
485454502F312E3120323030204F4B 0D0A
5365727665723A206D63727374726D20312E302D32332E39202870726F6429207374616E64617264205B4C696E757820332E31362E302D33302D6C6F776C6174656E6379207838365F36345D 0D0A
436F6E74656E742D547970653A6170706C69636174696F6E2F6F637465742D73747265616D 0A
43616368652D436F6E74726F6C3A206E6F2D6361636865 0A
436F6E6E656374696F6E3A20636C6F7365 0D0A
0D0A
```

**Comment by azhurb** [comment]
Stalker doesn't do any streaming jobs. All it does is creates links based on those that have been specified in the admin panel. These links usually point to third-party streaming server, such as Wowza, udpxy, Flussonic etc.
The only place where it forms a stream is TV archive, but in this case, the links look like http://11.11.11.11:88/stalker_portal/storage/get.php

**Comment by fiery-** [comment]
Thanks. I suspected that this may be the case. At least IPTV providers may find this thread and try to fix their streaming servers.
